# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Droplet',
            fields=[
                ('drop_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data', models.TextField(max_length=200)),
                ('timestamp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='droplet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapi.User'),
        ),
    ]
