# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Droplet',
            fields=[
                ('drop_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(default='admin', verbose_name=25)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('data', models.TextField(max_length=200)),
                ('timestamp', models.TextField()),
            ],
        ),
    ]
