# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='droplet',
            old_name='user',
            new_name='user_id',
        ),
    ]
