# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droplet',
            name='owner',
            field=models.CharField(default='admin', max_length=25),
        ),
    ]
