# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0002_auto_20160402_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droplet',
            name='owner',
            field=models.CharField(max_length=25),
        ),
    ]
