# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0002_auto_20160325_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droplet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droplets', to=settings.AUTH_USER_MODEL),
        ),
    ]
